### ISSUE TITLE
Max Vertices per mesh is actually 32 instead of 32(k)

### ISSUE THREAD

**Issue by Ginnungr** [ASneakyFox/libgdx-fbxconv-gui#2]
In the configuration tab, the category "Max Verticies per mesh (k)" is set to 32 by default. But when an fbx file is loaded, the maximum vertices/indices option or the "-m" option is set to 32 instead of the actual fbx-conv default of 32767 or 32k.  This makes it so that meshes can't be combined as intended by fbx-conv.

Also, the "Max Verticies per mesh (k)" entry box in the configuration tab sets the maximum vertices/indices to literally the value in the box instead of that value multiplied by 1000 as indicated by (k) in the label.  Maybe instead, the box should continue to hold the literal value and the default changed to 32767 and the label changed to "Max Vertices per mesh".  The maximum value that can be held in the box would need to be increased too, since the current max is 50.  This way, there would be more control instead of having to go by increments of 1000.

Finally, Vertices is spelled incorrectly in the line "Max Verticies per mesh (k)"

**Comment by ASneakyFox** [comment]
Hey Ginnungr,

Thank you for the bug report. I have fixed this issue in the latest release (1.5)

https://github.com/ASneakyFox/libgdx-fbxconv-gui/releases/tag/1.5


-Daniel
